# Generated by Django 4.2.14 on 2024-07-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_commission', models.DecimalField(db_comment='판매 수수료(%)', decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(db_comment='계약 시작 날짜', null=True)),
                ('end_date', models.DateField(db_comment='계약 종료 날짜', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(db_comment='시', max_length=128)),
                ('gu', models.CharField(db_comment='구', max_length=128)),
                ('gun', models.CharField(db_comment='군', max_length=128)),
                ('dongmyun', models.CharField(db_comment='동, 면, 읍', max_length=128)),
                ('lat', models.FloatField(db_comment='위도')),
                ('lng', models.FloatField(db_comment='경도')),
                ('detail', models.CharField(db_comment='상세 주소', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='음식점 가게명', max_length=128)),
                ('tel_num', models.CharField(db_comment='음식점 연락처', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_type', models.CharField(choices=[('food', '배달 음식'), ('grocery', '식료품/가공식품'), ('pet_food', '반려동물식품')], db_comment='상점 유형', max_length=32)),
                ('store_name_display_only', models.CharField(db_comment='직원이 해당 상점을 한 눈에 볼 수 있게 관리하는 필드', max_length=128)),
                ('description', models.TextField(db_comment='상점 소개 문구')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.storeaddress')),
            ],
            options={
                'db_table': 'store',
                'db_table_comment': '상점',
            },
        ),
    ]
